name: Set up Bun and dependencies
description: Runs all the setup steps required to have Bun and all dependencies installed
inputs:
    bun-version:
        description: "Bun version to use"
        required: false
        default: "latest"
runs:
    using: composite
    steps:
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
              bun-version: ${{ inputs.bun-version }}

        - name: Setup Node.js (for npm publish)
          uses: actions/setup-node@v4
          with:
              node-version: "22"
              registry-url: "https://registry.npmjs.org"

        - name: List versions
          run: |
              echo "Versions:"
              echo "Bun $(bun --version)"
              echo "Node $(node --version)"
          shell: bash

        - name: Install dependencies
          run: bun install --frozen-lockfile
          shell: bash
